### ISSUE TITLE
How to run the AR algorithm without Multi-step optimization in your code

### ISSUE THREAD

**Issue by zyh1999** [garrett4wade/revisiting_marl#1]
Hello,
Thanks for the code base and indeed a really good work!
I was trying to replicate the results from the paper and started with bridge environment with PG-AR，PG-AR w.o. MO and PG-AR w.o.RO.
However, I don't know how to change some setting to train  PG-AR w.o. MO.  As for PG-AR w.o. RO, I can set "random_order" False to train, how about PG-AR w.o. MO?

**Comment by garrett4wade** [comment]
Hi, you can replace `AutoRegressiveMAPPO` with the ordinary `MAPPO` trainer [here](https://github.com/garrett4wade/revisiting_marl/blob/main/runner/shared_runner.py#L13), i.e., changing this line with
`from algorithm.trainers.mappo import MAPPO` and modifying [here](https://github.com/garrett4wade/revisiting_marl/blob/main/runner/shared_runner.py#L89) correspondingly.

**Comment by zyh1999** [comment]
Now I did as you said, then  it raised an error at  "action_log_probs, values, dist_entropy = self.policy.analyze(sample)"(line 95 in mappo.py). So I changed the “type” from "bridge_ar" to "actor-critic"(around line 22 in bridge.yaml), then the project will use "actor_critic_policy" instead of "ar_policy". But it still raise an error at "obs_dim = x.obs.shape[-1]"(line 204 in actor_critic_policy.py). Finally I switched the "agent_specific_obs" to "False" in bridge.yaml and it can run normally.

So, Does this code not support the ordinary mappo to use "agent_specific_obs" to run?

**Comment by garrett4wade** [comment]
Hi, the `analyze` method of an AR policy returns 2 more values than an ordinary actor-critic policy, which are `joint_entropy` and `all_execution_mask` (see the difference between [here](https://github.com/garrett4wade/revisiting_marl/blob/main/algorithm/trainers/mappo.py#L95) and [here](https://github.com/garrett4wade/revisiting_marl/blob/main/algorithm/trainers/ar_mappo.py#L15)). `joint_entropy` is not used for training and you can ignore it. `all_execution_mask` is necessary for multi-step optimization as it indicates the execution order of all agents, but the ordinary MAPPO does not require it.

To run PG w.o. MO, you should combine the AR policy with the ordinary MAPPO. You can either follow my previous comment and additionally add 2 more unused return values [in MAPPO](https://github.com/garrett4wade/revisiting_marl/blob/main/algorithm/trainers/mappo.py#L95), or replace the code between [L18](https://github.com/garrett4wade/revisiting_marl/blob/main/algorithm/trainers/ar_mappo.py#L18) and [L25](https://github.com/garrett4wade/revisiting_marl/blob/main/algorithm/trainers/ar_mappo.py#L25) with [this line](https://github.com/garrett4wade/revisiting_marl/blob/main/algorithm/trainers/mappo.py#L97).

I'll fix it later.

**Comment by zyh1999** [comment]
Ok, I understand that. Thank you!
